sudo: required
services:
  - docker 


before_install:
  - docker build -t kararha/dockapp -f Dockerfile.dev .


script: 
  - docker run kararha/dockapp npm run test -- --coverage


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dockapp"
  env: "Dockapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-029940143329"
  bucket_path: "dockapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
